name: priima_lounas_flutter
description: Priima lounas restaurant menu
publish_to: 'none'
version: 1.0.9+9

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  pull_to_refresh: ^2.0.0
  expansion_tile_card: ^2.0.0
  tuple: ^2.0.0
  path_provider: ^2.0.5
  store_redirect: ^2.0.0
  url_launcher: ^6.0.12
  device_info_plus: ^3.0.1

dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
  fonts:
    - family: PrimaLounasIcons
      fonts:
        - asset: fonts/PrimaLounasIcons.ttf
    - family: PriimaLounasTrophies
      fonts:
        - asset: fonts/PriimaLounasTrophies.ttf